### ISSUE TITLE
Consider using autoflake8

### ISSUE THREAD

**Issue by danlamanna** [kitware-resonant/cookiecutter-resonant#136]
I find myself running this manually to get unused import checks to pass:
```
find . -type f -name "*.py" -not -wholename "*.tox*" -exec  autoflake -i --remove-all-unused-imports  {} \+
```

(This should probably use `git ls-files`).

**Comment by brianhelba** [comment]
@danlamanna Is this obsolete in light of Ruff?

**Comment by danlamanna** [comment]
Definitely.
